board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('<int:article_id>/', views.article_detail, name='article_detail'),
    path('create/', views.create_article, name='create_article'),
    path('<int:article_id>/delete/', views.delete_article, name='delete_article'),
    path('<int:article_id>/update/', views.update_article, name='update_article'),

    path('<int:article_id>/comments/create/', views.create_comment, name='create_comment'),  # board/1/comments/create에 댓글을 쓰겠다
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
]

first_local/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('sns/', include('sns.urls')),
]

# dev 에서는 꼭 써야 함. (DEBUG=True)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sns/urls.py
from django.urls import path
from . import views

app_name = 'sns'

urlpatterns = [
    path('', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('create/', views.create_posting, name='create_posting'),

    path('<int:posting_id>/comment/create/', views.create_comment, name='create_comment'),
]

board/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.TextField(default='')
    content = models.TextField(default='')
    like = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.id}: {self.title[:20]}'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE )
    content = models.TextField(default='')

    def __str__(self):
        return f'{self.article.title}: {self.content[:20]}'

sns/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFit

# Create your models here.


class Posting(models.Model):
    content = models.TextField(default='')
    icon = models.CharField(max_length=20, default='')

    # Save as origin
    # image = models.ImageField(blank=True, upload_to='postings/%Y%M%d')

    # Save resized version
    image = ProcessedImageField(
        blank=True,
        upload_to='postings/resize/%Y%m%d',
        processors=[ResizeToFit(width=960, upscale=False)],
        format='JPEG'
    )

    image_thumbnail = ImageSpecField(
        source='image',
        processors=[ResizeToFit(width=320, upscale=False)],
        format='JPEG',
        options={'quality': 60}
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.content[:20]}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        string = f'\n=== Saved Posting with id: {self.id} ==='
        print(f'\n {string}')
        print(f'    content: {self.content}')
        if self.image:
            print(f'    image: {self.image.width}px {self.image.height}px: {self.image.size}')
        for i in range(len(string)-1):
            print('=', end="")
        print()


class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.posting.content[:10]}: {self.content[:20]}'

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Article, Comment
from IPython import embed


# from IPython import embed
# Create your views here.


def article_list(request):
    context = {}
    articles = Article.objects.all()
    context['articles'] = articles
    return render(request, 'board/list.html', context=context)


def article_detail(request, article_id):
    context = {}
    article = get_object_or_404(Article, id=article_id)
    comments = article.comment_set.all()

    context['article'] = article
    context['comments'] = comments

    return render(request, 'board/detail.html', context=context)


def create_article(request):
    if request.method == 'GET':
        return render(request, 'board/new.html')
    else:
        article = Article()

        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()

    return redirect('board:article_list')


def delete_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if request.method == 'GET':
        return redirect('board:article_detail', article_id)
    elif request.method == 'POST':
        article.delete()
        return redirect('board:article_list')


def update_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if request.method == 'GET':
        context = {}
        context['article'] = article
        return render(request, 'board/edit.html', context=context)
    else:
        title = request.POST.get('title')
        content = request.POST.get('content')

        article.title = title
        article.content = content
        article.save()

        return redirect('board:article_detail', article_id)


def create_comment(request, article_id):
    article = get_object_or_404(Article, id=article_id)

    if request.method == 'POST':
        comment = Comment()
        comment.content = request.POST.get('content')
        comment.article = article
        #comment.article_id = article.id 또한 가능
        comment.save()

    return redirect('board:article_detail', article.id)


def delete_comment(request, article_id, comment_id):
    article = get_object_or_404(Article, id=article_id)
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == 'POST':
        comment.delete()

    return redirect('board:article_detail', article.id)

sns/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Posting, Comment


# Create your views here.
def posting_list(request):
    postings = Posting.objects.order_by('-updated_at')
    context = {}
    context['postings'] = postings

    return render(request, 'sns/list.html', context=context)


def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comments = posting.comment_set.order_by('-created_at')
    context = {}
    context['posting'] = posting
    context['comments'] = comments

    return render(request, 'sns/detail.html', context=context)


def create_posting(request):
    if request.method == "POST":
        posting = Posting.objects.create(
            content=request.POST.get('content'),
            icon=request.POST.get('icon'),
            image=request.FILES.get('image'),
        )

        return redirect('sns:posting_detail', posting.id)

    else:
        return redirect('sns:posting_list')


def create_comment(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)

    if request.method == 'POST':
        content = request.POST.get('comment')
        comment = Comment()
        comment.content = content
        comment.posting = posting
        comment.save()

    return redirect('sns:posting_detail', posting.id)

board/templates/board/_comment.html
<div id="commentUI">
    <div id="commentForm">
        <form action="{% url 'board:create_comment' article.id %}" method="POST">
            {% csrf_token %}
            <label for="comment">comment</label>
            <input type="text" id="comment" name="content" placeholder="Hit Enter" autofocus>
        </form>
    </div>

    <div id="commentList">
        <ul>
            {% for comment in comments %}
                <li>{{ comment.content }}</li>
                <form action="{% url 'board:delete_comment' article.id comment.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" onclick="return confirm('삭제하시겠습니까?')">delete</button>
                </form>
            {% endfor %}
        </ul>
    </div>
</div>

board/templates/board/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Board-{% block title %}{% endblock %}</title>
</head>
<body>
    {% block button %}
    {% endblock %}

    {% block body %}

    {% endblock %}
</body>
</html>

board/templates/board/detail.html
{% extends 'board/base.html' %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block button %}
    <button>
        <a href="{% url 'board:article_list' %}">To Article List</a>
    </button>
{% endblock %}

{% block body %}
    <h2>{{ article.title }}</h2>
    <p>{{ article.content }}</p>

    <div>
        <form action="{% url 'board:delete_article' article.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" onclick="return confirm('삭제하시겠습니까?')">delete</button>
        </form>
    </div>

    <div>
        <form action="{% url 'board:update_article' article.id %}" method="GET">
            {% csrf_token %}
            <button type="submit">update</button>
        </form>
    </div>

    <hr>
    {% include 'board/_comment.html' %}

{% endblock %}

board/templates/board/edit.html
{% extends 'board/base.html' %}

{% block title %}
edit
{% endblock %}

{% block button %}
    <button>
        <a href="{% url 'board:article_list' %}">To Article List</a>
    </button>
{% endblock %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        <div>
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" value="{{ article.title }}">
        </div>
        <div>
            <label for="content">Content:</label>
            <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea>
        </div>
        <div>
            <button type="submit">submit</button>
        </div>
    </form>
{% endblock %}

board/templates/board/list.html
{% extends 'board/base.html' %}

{% block title %}
    list
{% endblock %}

{% block button %}
    <button>
        <a href="{% url 'board:create_article' %}">New Article</a>
    </button>
{% endblock %}

{% block body %}
    <h1>Article List</h1>

    {% if articles %}
        <ul>
            {% for article in articles %}
                <li>
                    <a href="{% url 'board:article_detail' article.id %}">{{ article.title }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock %}

board/templates/board/new.html
{% extends 'board/base.html' %}

{% block title %}
    New Article
{% endblock %}

{% block button %}
    <a href="{% url 'board:article_list' %}">
        <button>To Article List</button>
    </a>
{% endblock %}

{% block body %}
    <h1>New Article</h1>
    <form method="POST">
        {% csrf_token %}
        <div>
            <label for="title">Title: </label>
            <input type="text" name="title" id="title">
        </div>

        <div>
            <label for="content">Content: </label>
            <textarea name="content" id="content" cols="30" rows="10"></textarea>
        </div>

        <div>
            <button type="submit">submit</button>
        </div>
    </form>
{% endblock %}

sns/templates/sns/_comment.html
<!-- comment card -->
<div class="col-12 col-md-6">
    <div class="card mb-2">
        <form action="{% url 'sns:create_comment' posting.id %}" method="POST" class="m-2">
            {% csrf_token %}
            <label for="comment">comment</label>
            <input type="text" name="content" id="comment" class="form-control" autofocus>
        </form>
    </div>
    <div class="card">
        <ul class="list-group list-group-flush">
            {% if comments %}
                {% for comment in comments %}
                    <li class="list-group-item mb-1">{{ comment.content }}</li>
                {% endfor %}
            {% else %}
                <li class="list-group-item mb-1">No comments yet...!</li>
            {% endif %}
        </ul>
    </div>
</div>

sns/templates/sns/_forms.html
<header class="mt-3">
    <form action="{% url 'sns:create_posting' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <!-- icon select tag -->
            <div class="col-auto my-1">
                <label for="icon" class="sr-only">icon</label>
                <select name="icon" id="icon" class="custom-select mr-sm-2">
                    <option value="fas fa-question">?</option>
                    <option value="far fa-smile">:)</option>
                    <option value="far fa-angry">:(</option>
                    <option value="far fa-smile-wink">;)</option>
                    <option value="fab fa-angrycreative">angry creative</option>
                </select>
            </div>
            <!-- content input tag -->
            <div class="col-sm-6 my-1">
                <label for="content" class="sr-only">content</label>
                <input type="text" name="content" id="content" class="form-control" placeholder="Feels like...?">
            </div>
            <!-- image/file input tag -->
            <div class="col-sm-4 my-1 input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Upload image</span>
                </div>
                <div class="custom-file">
                    <label for="image" class="custom-file-label">Select image</label>
                    <input type="file" name="image" id="image" class="custom-file-input" accept="image/*">
                </div>
            </div>
            <!-- submit button -->
            <div class="col-auto my-1">
                <button type="submit" class="btn btn-primary">submit</button>
            </div>

        </div>
    </form>
</header>

sns/templates/sns/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {#  bootstrap CDN  #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {#  font-awesome CDN  #}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>SNS</title>
</head>
<body>
<!-- nav bar -->
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a href="{% url 'sns:posting_list' %}" class="nav-link {% block is_list %}{% endblock %}">NewsFeed</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% block is_detail %}{% endblock %}">Posting</a>
    </li>
</ul>

<div class="container">
    {% block body %}

    {% endblock %}
</div>
{#  js CDN #}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

sns/templates/sns/detail.html
{% extends 'sns/base.html' %}

{% block is_detail %}active{% endblock %}

{% block body %}
    <div class="row mt-3">
        <div class="col-12 col-md-6">
            <div class="card">
                {% if posting.image %}
                    <img src="{{ posting.image.url }}"
                         alt="{{ posting.image }}"
                         class="'card-img-top image-fluid">

                {% else %}
                    <img src="http://picsum.photos/960/580/?random"
                         alt="random_image"
                         class="card-img-top image-fluid">

                {% endif %}

                <div class="card-body">
                    <i class="{{ posting.icon }} fa-2x"></i>
                    <hr>
                    <p class="card-text">
                        {{ posting.content }}
                    </p>
                </div>
            </div>
        </div>

        {% include 'sns/_comment.html' %}
    </div>
{% endblock %}

sns/templates/sns/list.html
{% extends 'sns/base.html' %}

{% block is_list %}active{% endblock %}

{% block body %}
    {% include 'sns/_forms.html' %}

    {% if postings %}
        <section class="card-columns mt-3">
            {% for posting in postings %}
                <article class="card mb-2">
                    <a href="{% url 'sns:posting_detail' posting.id %}">
                        {% if posting.image %}
                            <img src="{{ posting.image_thumbnail.url }}"
                                 alt="{{ posting.image }}"
                                 class="card-img-top image-fluid">
                        {% else %}
                            <img src="http://picsum.photos/32{{ forloop.counter }}/580/?random"
                                 alt="random-image-{{ forloop.counter }}"
                                 class="card-img-top image-fluid">
                        {% endif %}
                    </a>
                    <div class="card-body">
                        <i class="{{ posting.icon }} fa-2x"></i>
                    </div>
                </article>
            {% endfor %}
        </section>
    {% endif %}
{% endblock %}